---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: ci
  image: rancher/dapper:v0.5.4
  commands:
    - dapper ci
  volumes:
    - name: docker
      path: /var/run/docker.sock
  when:
    event:
    - push
    - pull_request
    - tag

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: "rancher/eks-operator"
    tag: "${DRONE_TAG}-amd64"
  when:
    event:
    - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---

kind: pipeline
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: ci
  image: rancher/dapper:v0.5.4
  commands:
    - dapper ci
  volumes:
    - name: docker
      path: /var/run/docker.sock
  when:
    event:
      - push
      - pull_request
      - tag

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: "rancher/eks-operator"
    tag: "${DRONE_TAG}-arm64"
  when:
    event:
      - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  image: plugins/manifest:1.0.2
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
      - linux/arm64
    target: "rancher/eks-operator:${DRONE_TAG}"
    template: "rancher/eks-operator:${DRONE_TAG}-ARCH"
  when:
    event:
      - tag
depends_on:
  - amd64
  - arm64
